name: Günlük Çoklu-Site Scraper

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run: python run.py
      - uses: actions/upload-artifact@v3
        with:
          name: aktuel-json
          path: aktuel.json
